- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: install mysql-server
      state: present

  - name: run the mysql server
    ansible.builtin.service:
       name: run mysqld
       state: started
       enabled: yes 
